ARG ALPINE_VERSION=3.19

FROM node:18.20.2-alpine${ALPINE_VERSION} AS builder
WORKDIR /build-stage
ENV NODE_ENV=production
COPY package*.json ./
RUN npm install -g @subql/cli@5.8.1 && npm ci
COPY . ./
RUN npm run codegen && npm run build

FROM onfinality/subql-node:v6.0.2 as runner
WORKDIR /app
COPY --from=builder /build-stage/dist /app/dist
COPY --from=builder /build-stage/project.yaml /app
COPY --from=builder /build-stage/schema.graphql /app
